/* Justin Tromp
 * Date: 01/21/2019
 * Email: trompj@oregonstate.edu
 * Description: Animal class is a parent class to four other classes. Class is set up to allow user to create an animal
 * for zoo simulation game. Base variables used include animalCost, foodCost, animalRevenue, numberBabies, and animalAge.
 * Member functions:
 * animal - Default constructor sets up user animal object by base values of 0.
 * getAnimalAge - Gets animal age value
 * getAnimalCost - Gets animal cost value.
 * getAnimalRevenue - Gets revenue generated by each animal.
 * getFoodCost - Gets food cost.
 * getNumberBabies - Gets the birth rate for animal.
 * increaseAnimalAge - Increases age of animal by 1 day.
*/

#ifndef ANIMAL_HPP
#define ANIMAL_HPP

const int baseFoodCost = 10;

class Animal {
protected:
    int animalAge;
    int animalCost;
    int numberBabies;
    double foodCost;
    double animalRevenue;

public:
    //Set base constructor for animal
    Animal();

    //Animal constructor to set age of animal from parameter
    Animal(int);

    //Get food cost
    double getFoodCost();

    //Get animal revenue for day
    double getAnimalRevenue();

    //Get number of possible babies
    int getNumberBabies();

    //Get animal cost
    double getAnimalCost();

    //Get the age of the animal
    int getAnimalAge();

    //Increases animal age by 1
    void increaseAnimalAge();

};


#endif //ANIMAL_HPP
